export const ADD_STUDENT_TO_STORE = "STORE.ADDSTUDENT";
export const ADD_PRODUCT_TO_STORE = "STORE.ADDPRODUCT";

export const ADD_HOBBY_TO_STUDENT = "STUDENT.ADDHOBBY";
export const FETCH_STUDENT_HOBBIES = "STUDENT.FETCHHOBBIES"